  0%|                                                                                                                         | 0/18627 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/christina/Documents/climsim_ds/main.py", line 354, in <module>
    main(args)
  File "/home/christina/Documents/climsim_ds/main.py", line 153, in main
    trainer_stdiff.trainer(args=args, train_loader=train_loader,
  File "/home/christina/Documents/climsim_ds/optimization/trainer_stdiff.py", line 88, in trainer
    out = model.forward(x=x_past)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christina/Documents/climsim_ds/models/architectures/conv_lstm_diff.py", line 71, in forward
    output[:,:,time_step] = h
    ~~~~~~^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (1) must match the existing size (8) at non-singleton dimension 1.  Target sizes: [16, 1, 32, 64].  Tensor sizes: [16, 8, 32, 64]
Traceback (most recent call last):
  File "/home/christina/Documents/climsim_ds/main.py", line 354, in <module>
    main(args)
  File "/home/christina/Documents/climsim_ds/main.py", line 153, in main
    trainer_stdiff.trainer(args=args, train_loader=train_loader,
  File "/home/christina/Documents/climsim_ds/optimization/trainer_stdiff.py", line 88, in trainer
    out = model.forward(x=x_past)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christina/Documents/climsim_ds/models/architectures/conv_lstm_diff.py", line 71, in forward
    output[:,:,time_step] = h
    ~~~~~~^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (1) must match the existing size (8) at non-singleton dimension 1.  Target sizes: [16, 1, 32, 64].  Tensor sizes: [16, 8, 32, 64]
Nr of Trainable Params on cuda:   1387521